### ISSUE TITLE
Checklist for tuw-release 2.0.11

### ISSUE THREAD

**Issue by adammccartney** [TU-Wien-dataLAB/Grader-Service#115]
**Description**

This branch targets a release of the jaas system, using the version number `2.0.11`, this refers to the tagged images that will be used within the deployment. The various version numbers for `chart`, `grader_convert`, `grader_labextension` and `grader_service` are to follow.

### multi-app 
- [ ] soft deadlines see issue #70 
- [x] `kubespawner` knows how to load the correlated image for `grader_service` (should match user notebook)

### labextension front-end
- [x] Update submission list on submit
- [x] Update all file lists on fetch
- [x] Remove automatic pull in feedback view
- [ ] Add show buttons in filebrowser (edit assignment, manual grade assignment) 
- [x] Table styling

### grader convert 
- [x] Revamp logs see issue #103 

### docs 

- [x] update images in user guide  (this has also been mentioned in issue #98  and has been done on the branch documentation/new-documentation)

### images 

- [ ] dependency updates for Chemistry Image (move this issue to gitlab) see also jira issue for packages
