### ISSUE TITLE
Migrate to JupyterLab 4.0

### ISSUE THREAD

**Issue by florian-jaeger** [TU-Wien-dataLAB/Grader-Service#85]
## Tasks 

Higher list ordering indicates higher priority

- [x] Fix failing git push on release assignment, issue #93 
- [x] Integrate changes from branch generated from issue #92 
- [ ] All file lists do not work currently, which needs fixing
- [X] Update all packages
- [X] Use updated cookiecutter template
- [ ] Replaces all `any` types from labextension which were added to make the extension buildable
- [X] Find a replacement for `cell.model.value` as it is no longer supported (for example in validator.py [62])
- [x] Fix the metadata operations because the metadata variable is currently read only, therefore each metadata edit does not work (for example in model.ts/creation mode)
- [x] Fix SIGKILL on Grader Window
- [x] Fix cell revert functionality 
- [x] Fix grading mode

**Comment by florian-jaeger** [comment]
I found a replacement for cell.model.value!
