### ISSUE TITLE
Stateful menu for student's AssignmentTable

### ISSUE THREAD

**Issue by adammccartney** [TU-Wien-dataLAB/Grader-Service#96]
**Is your feature request related to a problem? Please describe.**

Currently trying to figure out a way to implement the action functionality on the small buttons that appear in the "assignment table" view for students. What we want to do seems straight forward enough: 

Click [assignment table view] (icon A), then load view A   

An overview of the buttons and actions that need to be implemented:
```
  button        conditional display   display options           conditional action   action logic                                       Request   endpoint
  ------------- --------------------- ------------------------- -------------------- -------------------------------------------------- --------- ----------------------------------------------------------------------------------------------------------
  Edit          yes                   edit OR pull              yes                  (pull then load detail view) OR load detail view   GET       /lectures/{lect~id~}/assignments/{a~id~} OR /lectures/{lect~id~}/assignments/{a~id~}/submissions/{s~id~}
  Reset         no                    reset                     no                   reset ... animate?                                 ???       ???
  Submit        yes                   deadline over OR submit   yes                  none OR submit                                     PUT       /lectures/{lect~id~}/assignments/{a~id~}/submissions/{s~id~}
  Detail View   no                    looking glass             yes                  load detail view                                   GET       /lectures/{lect~id~}/assignments/{a~id~}
  Feedback      yes                   tick OR cross             yes                  load feedback page for specific assignment         GET       /user/user3/lab/tree/feedback/lect1/1/2/Untitled.html
```

***TODOs***
- [x] Edit dynamic icon
- [x] Edit action
- [x] Reset icon
- [x] Reset action
- [x] ~~Submit dynamic icon~~ no submit button
- [x] ~~Submit action~~ no action
- [x] Detail icon
- [x] Detail view action
- [x] Feedback dynamic icon
- [x] ~~Feedback action~~ no action
- [x] Deadline dynamic display

***Implementation notes***

I got into the weeds a bit trying to implement the feedback button. As stated above, it is needed at the level of the `AssignmentTable` component. It seems like it should be possible to load the data via the reactRouter as long as we are loading from a page that has an identifiable `root`. In this case it's the `LectureComponent` that has the `root`, so it seems like that any data we need to derive from the router needs to be derived here. Specifically we want to be able to load `assignment` and `submissions` as we do in the `AssignmentComponent`.

It feels like it should be possible to load the data from the router in the `LectureComponent` and then simply pass this onto the `AssignmentTable` component that will then use it to deduce some information about the state of feedback for the various assignments. 

Anyway, work in progress, mind dump as they say...

**What I'd like to know**
Is anyone else watching the number of requests that get fired off every time a page is loaded and wondering if there might be a bit of redundancy being generated?

**Comment by adammccartney** [comment]
p.s. I'm not currently even starting to wonder about loading the pages directly after the buttons are clicked

**Comment by adammccartney** [comment]
Ah okay, so actually I just hadn't really been grasping the power of the router to load data. It seems like it can be picky enough in terms of insisting on one loader function per route, but there is no problem with sticking a couple of subroutines in the one loader: 
```ts

export const loadLecture = async (lectureId: number) => {
  try {
    const lecture = await getLecture(lectureId);
    const assignments = await getAllAssignments(lecture.id);

    return { lecture, assignments };
  } catch (error: any) {
    enqueueSnackbar(error.message, {
      variant: 'error'
    });
  }
};

/*
 * Load submissions for all assignments in a lecture
 * */
export const loadSubmissions = async (lecture: Lecture, assignments: Assignment[]) => {
    try {
        const submissions = await Promise.all(
            assignments.map(async (assignment) => {
                const submissions = await getAllSubmissions(lecture.id, assignment.id, "none", false);
                return { assignment, submissions };
            })
        );
        return submissions;
    } catch (error: any) {
        enqueueSnackbar(error.message, {
            variant: 'error'
        });
    }
};

export const loadAssignmentTableData = async (lectureId: number) => {
    try {
        const { lecture, assignments } = await loadLecture(lectureId);
        const submissions = await loadSubmissions(lecture, assignments);
        return { lecture, assignments, submissions };
    } catch (error: any) {
        enqueueSnackbar(error.message, {
            variant: 'error'
        });
    }
};
```

**Comment by adammccartney** [comment]
@florian-jaeger & @meffmadd is it possible that the Figma drawing indicates a state for the "Work on it" column that is unreachable with the current git behavior? It appears as if the files are automatically pulled as soon as a (student) user is logged in and there is a (new) released assignment.
