### ISSUE TITLE
Change structure of user's home directory in labextension

### ISSUE THREAD

**Issue by meffmadd** [TU-Wien-dataLAB/Grader-Service#97]
**Is your feature request related to a problem? Please describe.**
The current structure of files (source, release, actual assignments, ect.) puts lectures in sub-directories of these top-level directories. However, different lectures should be the top level directories and other directories (source etc.) should be sub-directories. The advantage of this approach is that e.g. quotas can be set more easily for each lecture.

**Describe the solution you'd like**
The path generation in the frontend and server extension have to be changed. This will mostly concern usages of the `getFiles` function in the frontend and any occurence of `self.root_dir` in server extension. In the frontend, the components integrated in the original notebook view are also dependent on the file path as they parse the lecture code and assignment id from the path.

***TODOs***
- [x] Change path generation in usages of `getFiles`
- [x] Change paths in FileList props
- [x] Change paths in `openBrowser` and `openTerminal`
- [x] Change notebook components
- [x] Change all paths in server extension that use `self.root_dir`
- [x] Change path generation in GitService
- [x] Big change: configurable base path for grader labextension which needs to be passed to front-end as well (use `page_config` to pass traitlet value to frontend see: https://github.com/jupyterlab/jupyterlab/blob/fea2cf52ea980712af61e79262c35017e59bb712/jupyterlab/labhubapp.py#L13)
