### ISSUE TITLE
Documentation and developer tools are up-to-date

### ISSUE THREAD

**Issue by adammccartney** [TU-Wien-dataLAB/Grader-Service#98]
**Describe the solution you'd like**
User documentation should reflect the most recent updates, new features and any architectural changes that may have happened during recent development work (summer 2023).  Also try to refactor any automation workflows related to the development environment.

**Tasks**

***Index***
- [x] Update screen animation on index page to reflect new UI

***Installation***
- [x] double check that current instructions work! 
- [x] Test & possibly refactor install scripts

***Getting Started***
- [x] check that "User Roles" section is up to date with newest updates
- [ ] Update `grader-service-migrate` to include use of config file 

***User Guide***
- [x] Update screenshots
- [x] Make the distinction between "instructor" and "student" more explicit.
- [x] Add docs for always hidden test section

***Rest API***
- [x] Update auto-generated docs to reflect recent model changes

***Developer Guide***
- [x] Document the main workflows (parallel to User Guide/Assignment Lifecycle might be useful)
- [x] How to update models and regenerate API docs
- [ ] Document the database setup for development environment

***Automation Workflows for developers***
- [x] Test build scripts (possibly add a top-level makefile)
- [ ] Add docker-compose script? 
- [x] Automate the generation of models & REST API docs

**Comment by Chizobaonorh** [comment]
Hello i would love to contribute to this
